name: variable
on: [push]
jobs:
  variable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test Variable
        run: node client.js
        env:
          ABC: abc
